// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwJISSNTpOXnyJyg7ya7JCO1WMH1SaHAg',
    appId: '1:719002254678:web:de24b0b251c669c2276af7',
    messagingSenderId: '719002254678',
    projectId: 'projects4-3b402',
    authDomain: 'projects4-3b402.firebaseapp.com',
    storageBucket: 'projects4-3b402.firebasestorage.app',
    measurementId: 'G-RX52NN93BH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdN9hXhAlBEz4BaX-uM8JhLT-BpAnl6OY',
    appId: '1:719002254678:android:3ea261c0640cd950276af7',
    messagingSenderId: '719002254678',
    projectId: 'projects4-3b402',
    storageBucket: 'projects4-3b402.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAudKdKcutF4zeLyMavkvYJ940FbRB-_UM',
    appId: '1:719002254678:ios:09b54a7b3791566e276af7',
    messagingSenderId: '719002254678',
    projectId: 'projects4-3b402',
    storageBucket: 'projects4-3b402.firebasestorage.app',
    iosBundleId: 'com.mdsoft.tajamaesuperadmin.tajamaeSuperAdmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAudKdKcutF4zeLyMavkvYJ940FbRB-_UM',
    appId: '1:719002254678:ios:09b54a7b3791566e276af7',
    messagingSenderId: '719002254678',
    projectId: 'projects4-3b402',
    storageBucket: 'projects4-3b402.firebasestorage.app',
    iosBundleId: 'com.mdsoft.tajamaesuperadmin.tajamaeSuperAdmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwJISSNTpOXnyJyg7ya7JCO1WMH1SaHAg',
    appId: '1:719002254678:web:4d5ef4e5419138d1276af7',
    messagingSenderId: '719002254678',
    projectId: 'projects4-3b402',
    authDomain: 'projects4-3b402.firebaseapp.com',
    storageBucket: 'projects4-3b402.firebasestorage.app',
    measurementId: 'G-4E1K69B58Q',
  );
}
